version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
     - REDIS_HOST=redis
    links:
      - "redis"
  redis:
    image: "redis:alpine"
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    links:
    - "web"