export const PODCAST_HAS_ERRORED = 'PODCAST_HAS_ERRORED';
export const PODCAST_IS_LOADING = 'PODCAST_IS_LOADING';
export const PODCAST_FETCH_DATA_SUCCESS = 'PODCAST_FETCH_DATA_SUCCESS';
export const CURRENT_EPISODE = 'CURRENT_EPISODE';
export const GET_RECENT_EPISODES = 'GET_RECENT_EPISODES';
export const SET_PODCAST_TO_NULL = 'SET_PODCAST_TO_NULL';

export const ALL_SHOWS_INFO_LOADING = 'ALL_SHOWS_INFO_LOADING';
export const ALL_SHOWS_INFO_HAS_ERRORED = 'ALL_SHOWS_INFO_HAS_ERRORED';
export const ALL_SHOWS_INFO_DATA_SUCCESS = 'ALL_SHOWS_INFO_DATA_SUCCESS';